import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";




const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",  // Regular font
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",  // Bold font
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",  // Medium font
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",  // Semi-Bold font
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-poppins",  // Create a CSS variable for the font
});


export const metadata: Metadata = {
  title: "Pizza App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


      <body className={`${poppins.variable} antialiased`}>
        <div className=" fixed top-0 z-20 bg-navbar max-md:h-[6vh] md:h-[10vh] w-[100vw] border-b-[1px] border-customGrayDark">
          <Link href="/">Home</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
